#!/usr/bin/python
#tag-valid tags the current trunk as valid wrt specified tests

import os, sys, pysvn #from pysvn.tigris.org, python-svn in ubuntu

svn = pysvn.Client()
user = 'fritz'
local = '.'
repos = 'http://obermeyer.svnrepository.com/svn/johann'
X = pysvn.wc_status_kind.external

if __name__ == '__main__':

    #check for tag arguments
    if len(sys.argv) < 2:
        print "USAGE: tag-valid test1 [test2] [test3] [...]"
        print "SYNOPSIS: svn tags a copy of the trunk that passes various tests"
        sys.exit(0)

    #check that repository has no local changes (TODO allow mixed versions)
    svn.update(local)
    st = svn.status(local, get_all=False, ignore=True, ignore_externals=True)
    st = [s for s in st
            if s['text_status'] != X      #ignore externals
            and s['path'] != u'tag-valid' #allow local mods to this file
    ]
    if st:
        print "please svn commit the following changes before tagging valid:"
        for s in st:
            print '  ' + s['path']
        sys.exit(0)

    #add a tag
    rev = svn.info(local)['revision'].number
    name = sys.argv[:]
    name[0] = str(rev)
    name = '-'.join(name)
    message =  'passed tests: %s' % ', '.join(sys.argv[1:])

    #tag the trunk
    print "tagging valid version: %s" % name
    def getLogMessage (): return True, message
    svn.callback_get_log_message = getLogMessage
    svn.copy('.', '%s/tags/valid/%s' % (repos,name))
    svn.update(local)
    print "current tags:"
    os.system('svn ls %s/tags/valid | sort -r' % repos)

